services:

    _defaults:
        public: false
        autowire: true

    # repositories

    Angelov\Donut\Communities\Repositories\CommunitiesRepositoryInterface: '@app.communities.repositories.doctrine'

    app.communities.repositories.doctrine:
        class: 'Angelov\Donut\Communities\Repositories\DoctrineCommunitiesRepository'


    # form

    app.communities.form.community_type:
        class: 'Angelov\Donut\Communities\Form\CommunityType'
        arguments: ['@app.users.security.current_user', '@Angelov\Donut\Core\UuidGenerator\UuidGeneratorInterface']
        tags:
            - { name: 'form.type' }


    # command handlers

    app.communities.handlers.store:
        class: 'Angelov\Donut\Communities\Handlers\StoreCommunityCommandHandler'
        public: true
        tags:
            - { name: 'command_handler', handles: 'Angelov\Donut\Communities\Commands\StoreCommunityCommand' }

    app.communities.handlers.join:
        public: true
        class: 'Angelov\Donut\Communities\Handlers\JoinCommunityCommandHandler'
        tags:
            - { name: 'command_handler', handles: 'Angelov\Donut\Communities\Commands\JoinCommunityCommand' }

    app.communities.handlers.leave:
        public: true
        class: 'Angelov\Donut\Communities\Handlers\LeaveCommunityCommandHandler'
        tags:
            - { name: 'command_handler', handles: 'Angelov\Donut\Communities\Commands\LeaveCommunityCommand' }
