services:

    _defaults:
        public: true

    # command bus

    app.core.command_bus.default: '@app.core.command_bus.simplebus'

    app.core.command_bus.simplebus:
        class: 'Angelov\Donut\Core\CommandBus\SimpleBusAdapter'
        arguments: ['@command_bus']


    # event bus

    app.core.event_bus.default: '@app.core.event_bus.simplebus'

    app.core.event_bus.simplebus:
        class: 'Angelov\Donut\Core\EventBus\SimpleBusAdapter'
        arguments: ['@simple_bus.event_bus']


    # result lists

    app.core.result_lists.pagination.url_generator:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\RoutingPaginationUrlGenerator'
        arguments:
            - '@router'
            - '@app.core.result_lists.current_page_resolver'
            - '@app.core.result_lists.pagination.url_generator.routing_url_generator.route_name_resolver'
            - '@app.core.result_lists.pagination.url_generator.routing_url_generator.url_properties_resolver'

    app.core.result_lists.current_page_resolver:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\CurrentPageResolvers\RequestCurrentPageResolver'
        arguments: ['@request_stack']

    app.core.result_lists.pagination.url_generator.routing_url_generator.url_properties_resolver:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\UrlPropertiesResolver\RequestUrlPropertiesResolver'
        arguments: ['@request_stack']

    app.core.result_lists.pagination.url_generator.routing_url_generator.route_name_resolver:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\RouteNameResolver\RequestRouteNameResolver'
        arguments: ['@request_stack']

    app.core.result_lists.pagination.page_existence_checker:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\PageExistenceChecker\PageExistenceChecker'

    app.core.result_lists.pagination.renderers.twig:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\Renderers\TwigPaginationRenderer'
        arguments:
            - '@twig'
            - '@app.core.result_lists.pagination.url_generator'
            - '@app.core.result_lists.current_page_resolver'
            - '@app.core.result_lists.pagination.page_existence_checker'

    app.core.result_lists.pagination.twig.extension:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\PaginationRendererTwigExtension'
        arguments: ['@app.core.result_lists.pagination.renderers.twig']
        tags:
            - { name: 'twig.extension' }


    # uuid generator

    app.core.uuid_generator:
        class: 'Angelov\Donut\Core\UuidGenerator\DoctrineUuidGeneratorAdapter'
        arguments: ['@doctrine.orm.entity_manager', '@app.core.uuid_generator.base_doctrine_generator']

    app.core.uuid_generator.base_doctrine_generator:
        class: 'Doctrine\ORM\Id\UuidGenerator'
        public: false
