services:

    _defaults:
        public: false
        autowire: true


    # result lists

    Angelov\Donut\Core\ResultLists\Pagination\UrlGenerators\PaginationUrlGeneratorInterface: '@app.core.result_lists.pagination.url_generator'

    app.core.result_lists.pagination.url_generator:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\RoutingPaginationUrlGenerator'

    Angelov\Donut\Core\ResultLists\Pagination\CurrentPageResolvers\CurrentPageResolverInterface: '@app.core.result_lists.current_page_resolver'

    app.core.result_lists.current_page_resolver:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\CurrentPageResolvers\RequestCurrentPageResolver'

    Angelov\Donut\Core\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\UrlPropertiesResolver\UrlPropertiesResolverInterface: '@app.core.result_lists.pagination.url_generator.routing_url_generator.url_properties_resolver'

    app.core.result_lists.pagination.url_generator.routing_url_generator.url_properties_resolver:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\UrlPropertiesResolver\RequestUrlPropertiesResolver'

    Angelov\Donut\Core\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\RouteNameResolver\RouteNameResolverInterface: '@app.core.result_lists.pagination.url_generator.routing_url_generator.route_name_resolver'

    app.core.result_lists.pagination.url_generator.routing_url_generator.route_name_resolver:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\UrlGenerators\RoutingPaginationUrlGenerator\RouteNameResolver\RequestRouteNameResolver'

    Angelov\Donut\Core\ResultLists\Pagination\PageExistenceChecker\PageExistenceCheckerInterface: '@app.core.result_lists.pagination.page_existence_checker'

    Angelov\Donut\Core\ResultLists\Pagination\Renderers\PaginationRendererInterface: '@app.core.result_lists.pagination.renderers.twig'

    app.core.result_lists.pagination.page_existence_checker:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\PageExistenceChecker\PageExistenceChecker'

    app.core.result_lists.pagination.renderers.twig:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\Renderers\TwigPaginationRenderer'

    app.core.result_lists.pagination.twig.extension:
        class: 'Angelov\Donut\Core\ResultLists\Pagination\PaginationRendererTwigExtension'
        tags:
            - { name: 'twig.extension' }


    # uuid generator

    Angelov\Donut\Core\UuidGenerator\UuidGeneratorInterface: '@app.core.uuid_generator'

    app.core.uuid_generator:
        class: 'Angelov\Donut\Core\UuidGenerator\DoctrineUuidGeneratorAdapter'

    Doctrine\ORM\Id\UuidGenerator: '@app.core.uuid_generator.base_doctrine_generator'

    app.core.uuid_generator.base_doctrine_generator:
        class: 'Doctrine\ORM\Id\UuidGenerator'
        public: false
