services:

    _defaults:
        public: true
        autowire: true

    Angelov\Donut\Movies\MoviesList\MoviesListInterface: '@app.movies.movies_list'

    app.movies.movies_list:
        class: 'Angelov\Donut\Movies\MoviesList\DoctrineMoviesList'
