services:

    _defaults:
        public: false
        autowire: true

    # repositories

    Donut\Places\Repositories\CitiesRepositoryInterface: '@app.places.cities.repository.doctrine'

    app.places.cities.repository.default: '@app.places.cities.repository.doctrine'

    app.places.cities.repository.doctrine:
        class: 'Angelov\Donut\Places\Repositories\DoctrineCitiesRepository'
