services:

    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    # feed

    Angelov\Donut\Thoughts\ThoughtsFeed\ThoughtsFeedInterface: '@app.thoughts.feed'

    app.thoughts.feed:
        class: 'Angelov\Donut\Thoughts\ThoughtsFeed\DoctrineThoughtsFeed'
        arguments: ['@doctrine.orm.entity_manager', '@app.users.security.current_user']


    # repositories

    Angelov\Donut\Thoughts\Repositories\ThoughtsRepositoryInterface: '@app.thoughts.repositories.doctrine'

    app.thoughts.repositories.default: '@app.thoughts.repositories.doctrine'

    app.thoughts.repositories.doctrine:
        class: 'Angelov\Donut\Thoughts\Repositories\DoctrineThoughtsRepository'


    # form

    app.thoughts.form.thought_type:
        class: 'Angelov\Donut\Thoughts\Form\ThoughtType'
        arguments: ['@app.users.security.current_user', '@app.core.uuid_generator']
        tags:
            - { name: 'form.type' }


    # thoughts counter

    Angelov\Donut\Thoughts\ThoughtsCounter\ThoughtsCounterInterface: '@app.thoughts.thoughts_counter.ensuring_default_value'

    app.thoughts.thoughts_counter.default: '@app.thoughts.thoughts_counter.ensuring_default_value'

    Angelov\Donut\Thoughts\ThoughtsCounter\RedisThoughtsCounter: '@app.thoughts.thoughts_counter.redis'

    app.thoughts.thoughts_counter.redis:
        class: 'Angelov\Donut\Thoughts\ThoughtsCounter\RedisThoughtsCounter'

    Angelov\Donut\Thoughts\ThoughtsCounter\LoggingThoughtsCounter: '@app.thoughts.thoughts_counter.logging'

    app.thoughts.thoughts_counter.logging:
        class: 'Angelov\Donut\Thoughts\ThoughtsCounter\LoggingThoughtsCounter'
        arguments: ['@app.thoughts.thoughts_counter.redis', '@logger']

    app.thoughts.thoughts_counter.ensuring_default_value:
        class: 'Angelov\Donut\Thoughts\ThoughtsCounter\EnsuringDefaultValueThoughtCounter'
        arguments: ['@app.thoughts.thoughts_counter.logging']

    app.thoughts.thoughts_counter.twig.exstension:
        class: 'Angelov\Donut\Thoughts\ThoughtsCounter\Twig\ThoughtsCounterExtension'
        tags:
            - { name: 'twig.extension' }


    # command handlers

    app.thoughts.handlers.store:
        class: 'Angelov\Donut\Thoughts\Handlers\StoreThoughtCommandHandler'
        public: true
        tags:
            - { name: 'command_handler', handles: 'Angelov\Donut\Thoughts\Commands\StoreThoughtCommand' }

    app.thoughts.handlers.delete:
        class: 'Angelov\Donut\Thoughts\Handlers\DeleteThoughtCommandHandler'
        public: true
        tags:
            - { name: 'command_handler', handles: 'Angelov\Donut\Thoughts\Commands\DeleteThoughtCommand' }


    # event subscribers

    app.thoughts.event_subscribers.increase_thoughts_number_for_user:
        class: 'Angelov\Donut\Thoughts\EventSubscribers\IncreaseThoughtsNumberForUser'
        public: true
        tags:
            - { name: 'event_subscriber', subscribes_to: 'Angelov\Donut\Thoughts\Events\ThoughtWasPublishedEvent' }

    app.thoughts.event_subscribers.decrease_thoughts_number_for_user:
        class: 'Angelov\Donut\Thoughts\EventSubscribers\DecreaseThoughtsNumberForUser'
        public: true
        tags:
            - { name: 'event_subscriber', subscribes_to: 'Angelov\Donut\Thoughts\Events\ThoughtWasDeletedEvent' }
