services:

    _defaults:
        public: false
        autowire: true

    app.security.voter.delete_thought_voter:
        class: 'AppBundle\Security\Voter\DeleteThoughtVoter'
        tags:
            - { name: 'security.voter' }

    app.users.register_residency:
        class: 'AppBundle\FriendsSuggestions\RegisterUserResidencyInNeo4j'
        public: true
        tags:
            - { name: 'event_subscriber', subscribes_to: 'Angelov\Donut\Users\Events\UserRegisteredEvent' }


    app.users.send_welcoming_email:
        class: 'AppBundle\EventSubscribers\Users\SendWelcomingEmail'
        public: true
        tags:
            - { name: 'asynchronous_event_subscriber', subscribes_to: 'Angelov\Donut\Users\Events\UserRegisteredEvent' }

    app.core.faker:
        class: 'Faker\Generator'
        factory: ['Faker\Factory', 'create']

    AppBundle\Factories\CitiesFactory: '@app.factories.cities.faker'

    app.factories.cities.faker:
        class: 'AppBundle\Factories\CitiesFactory'

    AppBundle\Factories\UsersFactory: '@app.factories.users.faker'

    app.factories.users.faker:
        class: 'AppBundle\Factories\UsersFactory'

    app.factories.communities.faker:
        class: 'AppBundle\Factories\CommunitiesFactory'

    app.factories.thoughts.faker:
        class: 'AppBundle\Factories\ThoughtsFactory'

    app.factories.friendships:
        class: 'AppBundle\Factories\FriendshipsFactory'



    app.api.serialization.community:
        class: 'ApiBundle\Serialization\CommunityHandler'
        tags:
            - { name: 'jms_serializer.subscribing_handler', type: 'Angelov\Donut\Communities\Community', format: 'json' }

    app.api.oauth2.commands.create_client:
        class: ApiBundle\Console\CreateClientCommand
        tags:
            - { name: console.command }

    GraphAware\Neo4j\Client\Client: "@neo4j.client.default"

    app.neo4j.client.default: "@neo4j.client.default"

    Predis\Client: '@snc_redis.default'