parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        options:
            1002: "SET sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))"
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Community:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../Donut/Communities'
                prefix: 'Angelov\Donut\Communities'
            User:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../Donut/Users'
                prefix: 'Angelov\Donut\Users'
            Thought:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../Donut/Thoughts'
                prefix: 'Angelov\Donut\Thoughts'
            Friendships:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../Donut/Friendships'
                prefix: 'Angelov\Donut\Friendships'
            FriendshipRequests:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../Donut/Friendships/FriendshipRequests'
                prefix: 'Angelov\Donut\Friendships\FriendshipRequests'
            Movies:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../Donut/Movies'
                prefix: 'Angelov\Donut\Movies'
            Places:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../Donut/Places'
                prefix: 'Angelov\Donut\Places'
            OAuth2:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../ApiBundle/Oauth2'
                prefix: 'ApiBundle\Oauth2'