fos_rest:
    routing_loader:
        default_format: json
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/.*', fallback_format: 'json' }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
