fos_rest:

    body_listener: false
    routing_loader: false
    format_listener:
        enabled: true
        rules:
            - { path: '^/api/.*', fallback_format: 'json' }
            - { path: ^/, priorities: ['html', '*/*'], fallback_format: html, prefer_extension: true }
