language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

cache:
  directories:
    - vendor/

services:
  - mysql
  - redis-server
  - rabbitmq

before_install:
  - mv etc/travis/.env.test .env.test
  - sudo apt-get update > /dev/null
  - sh -c ./etc/travis/install-jdk8.sh
  - sh -c ./etc/travis/install-neo4j.sh

install: composer install

before_script:
  - APP_ENV=test mysql -e 'CREATE DATABASE IF NOT EXISTS donut_test;'
  # - ./bin/console doctrine:database:create --env=test
  - APP_ENV=test ./bin/console doctrine:migrations:migrate --no-interaction --quiet
  - mv etc/travis/phpunit.xml phpunit.xml

script:
  - vendor/bin/phpspec run --format=dot
  - vendor/bin/phpunit
  - vendor/bin/behat --format=progress

notifications:
  email: false
