language: php

php:
  - '7.1'

cache:
  directories:
    - vendor/

jobs:
  include:
    - stage: static analysis
      before_install:
        - git clone https://github.com/nikic/php-ast.git
        - cd php-ast
        - phpize
        - ./configure
        - make install
        - echo "extension=ast.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
        - cd ..
        - phpenv config-rm xdebug.ini
      install:
        - composer install
        - composer require etsy/phan
      script:
        - vendor/bin/phan --config-file=etc/phan-config.php

    - stage: test
      services:
        - mysql
        - redis-server
        - rabbitmq
      before_install:
        - sudo apt-get update > /dev/null
        - sh -c ./etc/travis/install-jdk8.sh
        - sh -c ./etc/travis/install-neo4j.sh
      install: composer install
      before_script:
        - mv etc/travis/.env .env
        - mysql -e 'CREATE DATABASE IF NOT EXISTS donut_test;'
      # - ./bin/console doctrine:database:create --env=test
        - ./bin/console doctrine:migrations:migrate --env=test --no-interaction --quiet
      script:
        - vendor/bin/phpspec run --format=dot
        - vendor/bin/phpunit
        - vendor/bin/behat --format=progress

  allow_failures:
    - stage: static analysis

notifications:
  email: false
