language: php

php:
  - '7.1'

services:
  - mysql
  - redis-server
  - rabbitmq

cache:
  directories:
    - vendor/

before_install:
  - sudo apt-get update > /dev/null
  - sh -c ./etc/travis/install-jdk8.sh
  - sh -c ./etc/travis/install-neo4j.sh

install:
  - composer install

before_script:
  - mv etc/travis/parameters.yml app/config/parameters.yml
  - mysql -e 'CREATE DATABASE IF NOT EXISTS donut_test;'
# - ./bin/console doctrine:database:create --env=test
  - ./bin/console doctrine:migrations:migrate --env=test --no-interaction --quiet

script:
  - vendor/bin/phpspec run --format=dot
  - vendor/bin/phpunit
  - vendor/bin/behat --format=progress

notifications:
  email: false
