version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: donut-redis
      ports:
        - "6379:6379"

    mysql:
      image: mysql:5.7
      container_name: donut-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=donut
        - MYSQL_USER=donut
        - MYSQL_PASSWORD=donut
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: donut-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./etc/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: etc/docker/php-fpm
      container_name: donut-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./etc/docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

    neo4j:
      image: neo4j:latest
      container_name: donut-neo4j
      environment:
       - NEO4J_AUTH=neo4j/blabla
      ports:
        - "7474:7474"
        - "7687:7687"

    rabbit_mq:
      image: rabbitmq:3-management
      container_name: donut-rabbit-mq
      ports:
        - "8090:15672"
        - "5672:5672"
        - "5671:5671"
      environment:
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_VHOST: vhost

# Initial docker-compose.yml file generated with phpdocker.io