imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Community:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../src/SocNet/Communities'
                prefix: 'SocNet\Communities'
            User:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../src/SocNet/Users'
                prefix: 'SocNet\Users'
            Thought:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../src/SocNet/Thoughts'
                prefix: 'SocNet\Thoughts'
            Friendships:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../src/SocNet/Friendships'
                prefix: 'SocNet\Friendships'
            FriendshipRequests:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../src/SocNet/Friendships/FriendshipRequests'
                prefix: 'SocNet\Friendships\FriendshipRequests'
            Movies:
                type: annotation
                is_bundle: false
                dir: '%kernel.root_dir%/../src/SocNet/Movies'
                prefix: 'SocNet\Movies'

doctrine_migrations:
    dir_name: '%kernel.root_dir%/Resources/migrations'

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://localhost

neo4j:
  connections:
    default:
      schema: bolt
      host: "%neo4j_host%"
      port: "%neo4j_port%"
      username: "%neo4j_username%"
      password: "%neo4j_password%"
