app:
    resource: "@AppBundle/Controller/"
    type:     annotation

api:
    resource: "@ApiBundle/Controller/"
    type:     rest
    prefix:   api

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"