services:

    app.security.login_form_authenticator:
        class: 'AppBundle\Security\LoginFormAuthenticator'
        arguments:
            - '@form.factory'
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@security.password_encoder'

    app.security.voter.administrator_voter:
        class: 'AppBundle\Security\Voter\AdministratorVoter'
        tags:
            - { name: 'security.voter' }

    app.security.voter.thought_author_voter:
        class: 'AppBundle\Security\Voter\ThoughtAuthorVoter'
        tags:
            - { name: 'security.voter' }

    app.doctrine.hash_password_listener:
        class: 'AppBundle\Doctrine\HashPasswordListener'
        arguments: ['@security.password_encoder']
        tags:
            - { name: doctrine.event_subscriber }

    app.thoughts_counter.default: '@app.thoughts_counter.redis'

    app.thoughts_counter.db:
        class: 'AppBundle\ThoughtsCounter\DbThoughtsCounter'

    app.thoughts_counter.redis:
        class: 'AppBundle\ThoughtsCounter\RedisThoughtsCounter'
        arguments:
            - '@snc_redis.default'

    app.thoughts_counter_exstension:
        class: 'AppBundle\Twig\Extension\ThoughtsCounterExtension'
        arguments:
            - '@app.thoughts_counter.default'
        tags:
            - { name: 'twig.extension' }
