imports:
    - { resource: 'services/to_refactor.yml' }

    - { resource: 'services/core.yml' }
    - { resource: 'services/users.yml' }
    - { resource: 'services/thoughts.yml' }
    - { resource: 'services/communities.yml' }
    - { resource: 'services/friendships.yml' }
