services:

    app.security.login_form_authenticator:
        class: 'AppBundle\Security\LoginFormAuthenticator'
        arguments:
            - '@form.factory'
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@security.password_encoder'

    app.security.voter.delete_thought_voter:
        class: 'AppBundle\Security\Voter\DeleteThoughtVoter'
        tags:
            - { name: 'security.voter' }

    app.doctrine.hash_password_listener:
        class: 'AppBundle\Doctrine\HashPasswordListener'
        arguments: ['@security.password_encoder']
        tags:
            - { name: doctrine.event_subscriber }

    app.thoughts_counter.default: '@app.thoughts_counter.redis'

    app.thoughts_counter.db:
        class: 'AppBundle\ThoughtsCounter\DbThoughtsCounter'

    app.thoughts_counter.redis:
        class: 'AppBundle\ThoughtsCounter\RedisThoughtsCounter'
        arguments:
            - '@snc_redis.default'

    app.thoughts_counter_exstension:
        class: 'AppBundle\Twig\Extension\ThoughtsCounterExtension'
        arguments:
            - '@app.thoughts_counter.default'
        tags:
            - { name: 'twig.extension' }

    app.friendships.friends_recommender.friendship_recorder.default: '@app.friendships.friends_recommender.friendship_recorder.neo4j'

    app.friendships.friends_recommender.friendship_recorder.neo4j:
        class: 'AppBundle\FriendsRecommender\Neo4JFriendsRecommender\Neo4jFriendshipRecorder'
        arguments:
            - '@neo4j.client.default'

    app.mutual_friends_resolver.default: '@app.mutual_friends_resolver.neo4j'

    app.mutual_friends_resolver.neo4j:
        class: AppBundle\MutualFriendsResolver\Neo4jMutualFriendsResolver
        arguments:
            - '@neo4j.client.default'
            - '@app.users.repository'

    app.users.repository:
            class: Doctrine\ORM\EntityRepository
            factory: ["@doctrine.orm.entity_manager", getRepository]
            arguments:
                - AppBundle\Entity\User

    app.mutual_friends_exstension:
          class: 'AppBundle\Twig\Extension\MutualFriendsExtension'
          arguments:
              - '@app.mutual_friends_resolver.default'
          tags:
              - { name: 'twig.extension' }