services:

    app.security.login_form_authenticator:
        class: 'AppBundle\Security\LoginFormAuthenticator'
        arguments:
            - '@form.factory'
            - '@app.users.repository.default'
            - '@router'
            - '@security.password_encoder'

    app.security.voter.delete_thought_voter:
        class: 'AppBundle\Security\Voter\DeleteThoughtVoter'
        tags:
            - { name: 'security.voter' }

    app.doctrine.hash_password_listener:
        class: 'AppBundle\Doctrine\HashPasswordListener'
        arguments: ['@security.password_encoder']
        tags:
            - { name: doctrine.event_subscriber }

    app.thoughts_counter.default: '@app.thoughts_counter.redis'

    app.thoughts_counter.db:
        class: 'AppBundle\ThoughtsCounter\DbThoughtsCounter'

    app.thoughts_counter.redis:
        class: 'AppBundle\ThoughtsCounter\RedisThoughtsCounter'
        arguments:
            - '@snc_redis.default'
            - '@logger'

    app.thoughts_counter_exstension:
        class: 'AppBundle\Twig\Extension\ThoughtsCounterExtension'
        arguments:
            - '@app.thoughts_counter.default'
        tags:
            - { name: 'twig.extension' }

    app.mutual_friends_resolver.default: '@app.mutual_friends_resolver.neo4j'

    app.mutual_friends_resolver.neo4j:
        class: AppBundle\MutualFriendsResolver\Neo4jMutualFriendsResolver
        arguments:
            - '@neo4j.client.default'
            - '@app.mutual_friends_resolver.users_provider.repository'

    app.mutual_friends_resolver.users_provider.repository:
        class: AppBundle\MutualFriendsResolver\UsersProvider\RepositoryUsersProvider
        arguments:
            - '@app.users.repository.default'

    app.mutual_friends_resolver.users_provider.fake:
        class: AppBundle\MutualFriendsResolver\UsersProvider\FakeUsersProvider

    app.mutual_friends_resolver.users_provider.qb:
        class: AppBundle\MutualFriendsResolver\UsersProvider\QueryBuilderUsersProvider
        arguments:
            - '@doctrine.orm.entity_manager'

    app.users.repository.default: '@app.users.repository.doctrine'

    app.users.repository.doctrine:
        class: AppBundle\Repository\DoctrineUsersRepository
        arguments:
            - '@app.doctrine.repository.users'

    app.doctrine.repository.users:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - AppBundle\Entity\User

    app.mutual_friends_exstension:
          class: 'AppBundle\Twig\Extension\MutualFriendsExtension'
          arguments:
              - '@app.mutual_friends_resolver.default'
          tags:
              - { name: 'twig.extension' }

    ### core

    app.core.security.current_user_resolver:
        class: 'SocNet\Core\Security\CurrentUserResolver'
        arguments: ['@security.token_storage']

    app.core.security.current_user:
        class: 'AppBundle\Entity\User'
        factory: ['@app.core.security.current_user_resolver', 'getUser']

    ### communities

    app.communities.repositories.default: '@app.communities.repositories.doctrine'

    app.communities.repositories.doctrine:
        class: 'SocNet\Communities\Repositories\DoctrineCommunitiesRepository'
        arguments: ['@doctrine.orm.entity_manager']

    app.communities.form.community_type:
        class: 'SocNet\Communities\Form\CommunityType'
        arguments: ['@app.core.security.current_user']
        tags:
            - { name: 'form.type' }

    app.communities.handlers.store:
        class: 'SocNet\Communities\Handlers\StoreCommunityCommandHandler'
        arguments: ['@app.communities.repositories.default']
        tags:
            - { name: 'command_handler', handles: 'SocNet\Communities\Commands\StoreCommunityCommand' }

    app.communities.handlers.join:
        class: 'SocNet\Communities\Handlers\JoinCommunityCommandHandler'
        arguments: ['@app.communities.repositories.default']
        tags:
            - { name: 'command_handler', handles: 'SocNet\Communities\Commands\JoinCommunityCommand' }

    app.communities.handlers.leave:
        class: 'SocNet\Communities\Handlers\LeaveCommunityCommandHandler'
        arguments: ['@app.communities.repositories.default']
        tags:
            - { name: 'command_handler', handles: 'SocNet\Communities\Commands\LeaveCommunityCommand' }