services:

    app.security.login_form_authenticator:
        class: 'AppBundle\Security\LoginFormAuthenticator'
        arguments:
            - '@form.factory'
            - '@doctrine.orm.entity_manager'
            - '@router'
            - '@security.password_encoder'

    app.doctrine.hash_password_listener:
        class: 'AppBundle\Doctrine\HashPasswordListener'
        arguments: ['@security.password_encoder']
        tags:
            - { name: doctrine.event_subscriber }

    app.thoughts_counter.default: '@app.thoughts_counter.db'

    app.thoughts_counter.db:
        class: 'AppBundle\ThoughtsCounter\DbThoughtsCounter'