app:
    resource: "../src/AppBundle/Controller/"
    type:     annotation

api:
    resource: "../../src/ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
