services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    app.core.faker:
        class: 'Faker\Generator'
        factory: ['Faker\Factory', 'create']

    AppBundle\Factories\:
        resource: '../src/AppBundle/Factories/*'
