services:

    # repositories

    app.communities.repositories.default: '@app.communities.repositories.doctrine'

    app.communities.repositories.doctrine:
        class: 'SocNet\Communities\Repositories\DoctrineCommunitiesRepository'
        arguments: ['@doctrine.orm.entity_manager']


    # form

    app.communities.form.community_type:
        class: 'SocNet\Communities\Form\CommunityType'
        arguments: ['@app.users.security.current_user', '@app.core.uuid_generator']
        tags:
            - { name: 'form.type' }


    # command handlers

    app.communities.handlers.store:
        class: 'SocNet\Communities\Handlers\StoreCommunityCommandHandler'
        arguments: ['@app.communities.repositories.default']
        tags:
            - { name: 'command_handler', handles: 'SocNet\Communities\Commands\StoreCommunityCommand' }

    app.communities.handlers.join:
        class: 'SocNet\Communities\Handlers\JoinCommunityCommandHandler'
        arguments: ['@app.communities.repositories.default']
        tags:
            - { name: 'command_handler', handles: 'SocNet\Communities\Commands\JoinCommunityCommand' }

    app.communities.handlers.leave:
        class: 'SocNet\Communities\Handlers\LeaveCommunityCommandHandler'
        arguments: ['@app.communities.repositories.default']
        tags:
            - { name: 'command_handler', handles: 'SocNet\Communities\Commands\LeaveCommunityCommand' }
