services:

    # command bus

    app.core.command_bus.default: '@app.core.command_bus.simplebus'

    app.core.command_bus.simplebus:
        class: 'SocNet\Core\CommandBus\SimpleBusAdapter'
        arguments: ['@command_bus']


    # event bus

    app.core.event_bus.default: '@app.core.event_bus.simplebus'

    app.core.event_bus.simplebus:
        class: 'SocNet\Core\EventBus\SimpleBusAdapter'
        arguments: ['@simple_bus.event_bus']
