services:

    app.security.voter.delete_thought_voter:
        class: 'AppBundle\Security\Voter\DeleteThoughtVoter'
        tags:
            - { name: 'security.voter' }

    app.users.register_residency:
        class: 'AppBundle\FriendsSuggestions\RegisterUserResidencyInNeo4j'
        arguments: ['@neo4j.client.default']
        tags:
            - { name: 'event_subscriber', subscribes_to: 'SocNet\Users\Events\UserRegisteredEvent' }


    app.users.send_welcoming_email:
        class: 'AppBundle\EventSubscribers\Users\SendWelcomingEmail'
        arguments: ['@mailer', '@twig']
        tags:
            - { name: 'event_subscriber', subscribes_to: 'SocNet\Users\Events\UserRegisteredEvent' }
