services:

    app.security.voter.delete_thought_voter:
        class: 'AppBundle\Security\Voter\DeleteThoughtVoter'
        tags:
            - { name: 'security.voter' }

    app.mutual_friends_exstension:
          class: 'AppBundle\Twig\Extension\MutualFriendsExtension'
          arguments:
              - '@app.mutual_friends_resolver.default'
          tags:
              - { name: 'twig.extension' }
