services:

    _defaults:
        public: true

    app.security.voter.delete_thought_voter:
        class: 'AppBundle\Security\Voter\DeleteThoughtVoter'
        tags:
            - { name: 'security.voter' }

    app.users.register_residency:
        class: 'AppBundle\FriendsSuggestions\RegisterUserResidencyInNeo4j'
        arguments: ['@neo4j.client.default']
        tags:
            - { name: 'event_subscriber', subscribes_to: 'Angelov\Donut\Users\Events\UserRegisteredEvent' }


    app.users.send_welcoming_email:
        class: 'AppBundle\EventSubscribers\Users\SendWelcomingEmail'
        arguments: ['@mailer', '@twig']
        tags:
            - { name: 'asynchronous_event_subscriber', subscribes_to: 'Angelov\Donut\Users\Events\UserRegisteredEvent' }

    app.core.faker:
        class: 'Faker\Generator'
        factory: ['Faker\Factory', 'create']

    app.factories.cities.faker:
        class: 'AppBundle\Factories\CitiesFactory'
        arguments: ['@app.core.faker', '@app.core.uuid_generator']

    app.factories.users.faker:
        class: 'AppBundle\Factories\UsersFactory'
        arguments: ['@app.core.faker', '@app.core.uuid_generator', '@app.factories.cities.faker']

    app.factories.communities.faker:
        class: 'AppBundle\Factories\CommunitiesFactory'
        arguments: ['@app.core.faker', '@app.core.uuid_generator', '@app.factories.users.faker']

    app.factories.thoughts.faker:
        class: 'AppBundle\Factories\ThoughtsFactory'
        arguments: ['@app.core.faker', '@app.core.uuid_generator', '@app.factories.users.faker']

    app.factories.friendships:
        class: 'AppBundle\Factories\FriendshipsFactory'
        arguments: ['@app.core.uuid_generator', '@app.factories.users.faker']



    app.api.serialization.community:
        class: 'ApiBundle\Serialization\CommunityHandler'
        tags:
            - { name: 'jms_serializer.subscribing_handler', type: 'Angelov\Donut\Communities\Community', format: 'json' }

    app.api.oauth2.commands.create_client:
        class: ApiBundle\Console\CreateClientCommand
        tags:
            - { name: console.command }